[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/corazzon/numpy-beginners/blob/main/03-04-numpy-array.ipynb) 

* [NumPy: the absolute basics for beginners — NumPy Manual](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
np.newaxis

In [4]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [5]:
a.shape, a2.shape

((6,), (1, 6))

In [6]:
a_list = [0, "1", 2.0, 3]
type(a_list)

list

In [7]:
np.array(a_list)

array(['0', '1', '2.0', '3'], dtype='<U21')

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
a[1]

array([5, 6, 7, 8])

## More information about arrays
## How to create a basic array

In [11]:
np.zeros(2)

array([0., 0.])

In [12]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(2)

array([1., 1.])

In [14]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [15]:
np.empty(2)

array([1., 1.])

In [16]:
np.empty([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [18]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### 배열 생성 속도 비교

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
# %timeit np.zeros(5)

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
# %timeit np.ones(5)

In [23]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [24]:
# %timeit np.empty(5)

In [25]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
# %timeit np.linspace(1, 10, 5)

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
# %timeit np.arange(5)