In [1]:
import numpy as np

## Adding, removing, and sorting elements


In [2]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [3]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# 역순정렬
np.sort(arr)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [5]:
np.random.seed(42)
a = np.random.randint(0, 10, 12).reshape([3, 4])
a

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

In [6]:
a.shape

(3, 4)

In [7]:
np.sort(a)

array([[3, 4, 6, 7],
       [2, 6, 6, 9],
       [3, 4, 7, 7]])

In [8]:
np.sort(a)[:, ::-1]

array([[7, 6, 4, 3],
       [9, 6, 6, 2],
       [7, 7, 4, 3]])

In [9]:
np.sort(a, axis=0)

array([[6, 3, 2, 4],
       [6, 4, 3, 6],
       [7, 9, 7, 7]])

In [10]:
np.sort(a, axis=0)[::-1, :]

array([[7, 9, 7, 7],
       [6, 4, 3, 6],
       [6, 3, 2, 4]])

In [11]:
np.random.seed(42)
a = np.random.randint(0, 10, 12).reshape([3, 4])
a

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

In [12]:
np.argsort(a)

array([[1, 3, 0, 2],
       [2, 0, 3, 1],
       [2, 1, 0, 3]])

In [13]:
np.argsort(a)[:, ::-1]

array([[2, 0, 3, 1],
       [1, 3, 0, 2],
       [3, 0, 1, 2]])

In [14]:
np.argsort(a, axis=0)

array([[0, 0, 1, 0],
       [1, 2, 2, 1],
       [2, 1, 0, 2]])

In [15]:
np.argsort(a, axis=0)[::-1, :]

array([[2, 1, 0, 2],
       [1, 2, 2, 1],
       [0, 0, 1, 0]])

In [16]:
# concat
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [17]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
x.shape, y.shape

((2, 2), (1, 2))

In [20]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## ndarray.ndim, ndarray.size, ndarray.shape

In [21]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [22]:
array_example.ndim

3

In [23]:
array_example.size

24

In [24]:
array_example.shape

(3, 2, 4)

## arr.reshape()

In [25]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [26]:
a.ndim

1

In [27]:
a.size

6

In [28]:
a.shape

(6,)

In [29]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [30]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

## np.newaxis, np.expand_dims

In [31]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [32]:
a.shape

(6,)

In [33]:
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [34]:
a2.shape

(1, 6)

In [35]:
row_vector = a[np.newaxis, :]
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [36]:
row_vector.shape

(1, 6)

In [37]:
col_vector = a[:, np.newaxis]
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [38]:
col_vector.shape

(6, 1)

In [39]:
b = np.expand_dims(a, axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
b = np.expand_dims(a, axis=0)
b

array([[1, 2, 3, 4, 5, 6]])