[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/corazzon/numpy-beginners/blob/main/09-10-indexing-slicing-stack-split-view-copy.ipynb) 

In [1]:
import numpy as np

## Indexing and slicing

* http://scipy-lectures.org/intro/numpy/array_object.html#manual-construction-of-arrays

<img src="http://scipy-lectures.org/_images/numpy_indexing.png" width="300" align="left">

<img src="http://scipy-lectures.org/_images/numpy_fancy_indexing.png" width="400" align="left">

<img src="https://numpy.org/doc/stable/_images/np_indexing.png" width="500" align="left">

In [2]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [3]:
data[0]

1

In [4]:
data[1]

2

In [5]:
data[0:2]

array([1, 2])

In [6]:
data[1:]

array([2, 3])

In [7]:
data[-2:]

array([2, 3])

In [8]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a[a < 5]

array([1, 2, 3, 4])

In [10]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [12]:
a[a % 2 != 0]

array([ 1,  3,  5,  7,  9, 11])

In [13]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
a[(a > 5) | (a == 5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [17]:
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [18]:
a[b]

array([1, 2, 3, 4])

In [19]:
not_there = np.nonzero(a == 42)
not_there

(array([], dtype=int64), array([], dtype=int64))

## How to create an array from existing data
* np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [20]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [22]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

a1, a2

(array([[1, 1],
        [2, 2]]),
 array([[3, 3],
        [4, 4]]))

In [23]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [24]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [25]:
x = np.arange(1, 25)
x.size

24

In [26]:
x = x.reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [27]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [28]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [29]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
b1 = a[0, :].copy()
b1

array([1, 2, 3, 4])

In [31]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [32]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])