In [1]:
import numpy as np

## Transposing and reshaping a matrix

In [2]:
data = np.arange(1, 7)
data

array([1, 2, 3, 4, 5, 6])

In [3]:
data.size

6

In [4]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [8]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [11]:
arr[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [12]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [14]:
np.flip(arr_2d, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [15]:
np.flip(arr_2d, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [16]:
arr_2d[1] = np.flip(arr_2d[1])
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [17]:
arr_2d[:, 1] = np.flip(arr_2d[:, 1])
arr_2d

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])

## .flatten(), ravel()

In [18]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
a1 = x.flatten()
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
a1[0] = 99
a1

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
a2 = x.ravel()
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
a2[0] = 99
a2

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
x

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
x.reshape(3, 4)

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## How to access the docstring for more information

In [28]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [29]:
max?

In [30]:
max??

In [31]:
# docstring 보기 : shift + tab
# max()

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [33]:
# a?

In [34]:
def double(a):
  '''
  Return a * 2
  '''
  return a * 2

In [35]:
# double?

In [36]:
# double??

In [37]:
# docstring 보기 : shift + tab
# np.arange()

##  Metrics
### MSE(Mean Squared Error)
<img src="https://numpy.org/doc/stable/_images/np_mse_viz1.png" width=500 align=left>

<img src="https://numpy.org/doc/stable/_images/np_MSE_implementation.png" width=500 align=left>

In [38]:
# 실제값 - 예측값의 차이의 제곱의 평균
# mse
predictions = np.ones(3, dtype=int)
labels = np.arange(1, 4)
# (predictions - labels) ** 2
mse = np.sum(np.square(predictions - labels)) * (1/3)
mse

1.6666666666666665

### RMSE(Root Mean Squared Error)

In [39]:
rmse = np.sqrt(mse)
rmse

1.2909944487358056

### MAE(Mean Absolute Error)

In [40]:
# 예측값과 실제값의 차이에 대한 절댓값의 평균
error = predictions - labels
mae = np.mean(np.abs(error))
mae

1.0

### MAPE(Mean Absolute Percentage Error)

In [41]:
# (실제값 - 예측값 / 실제값)의 절댓값에 대한 평균

np.mean(np.abs((predictions - labels) / labels))

0.38888888888888884