## How to save and load NumPy objects

In [17]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [18]:
np.save('filename', a)

In [19]:
b = np.load('filename.npy')
b

array([1, 2, 3, 4, 5, 6])

In [20]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
csv_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.savetxt('new_file.csv', csv_arr)

In [22]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [23]:
import pandas as pd

In [26]:
music = [['Billie Holiday', 'Jazz', 1300000, 27000000],
 ['Jimmie Hendrix', 'Rock', 2700000, 70000000],
 ['Miles Davis' ,'Jazz', 1500000, 48000000],
 ['SIA', 'Pop', 2000000, 74000000]]

In [29]:
df = pd.DataFrame(music)
df

0     1        2         3
0  Billie Holiday  Jazz  1300000  27000000
1  Jimmie Hendrix  Rock  2700000  70000000
2     Miles Davis  Jazz  1500000  48000000
3             SIA   Pop  2000000  74000000

In [32]:
df.to_csv("music.csv", index=False)

In [33]:
pd.read_csv("music.csv")

0     1        2         3
0  Billie Holiday  Jazz  1300000  27000000
1  Jimmie Hendrix  Rock  2700000  70000000
2     Miles Davis  Jazz  1500000  48000000
3             SIA   Pop  2000000  74000000

In [34]:
a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])
a

array([[-2.58289208,  0.43014843, -1.24082018,  1.59572603],
       [ 0.99027828,  1.17150989,  0.94125714, -0.14692469],
       [ 0.76989341,  0.81299683, -0.95068423,  0.11769564],
       [ 0.20484034,  0.34784527,  1.96979195,  0.51992837]])

In [35]:
df = pd.DataFrame(a)

In [36]:
df.to_csv('pd.csv')

In [37]:
pd.read_csv("pd.csv")

Unnamed: 0         0         1         2         3
0           0 -2.582892  0.430148 -1.240820  1.595726
1           1  0.990278  1.171510  0.941257 -0.146925
2           2  0.769893  0.812997 -0.950684  0.117696
3           3  0.204840  0.347845  1.969792  0.519928

In [38]:
np.savetxt('np.csv', a, fmt='%.2f', 
           delimiter=',', header='1,  2,  3,  4')

In [39]:
cat np.csv

# 1,  2,  3,  4
-2.58,0.43,-1.24,1.60
0.99,1.17,0.94,-0.15
0.77,0.81,-0.95,0.12
0.20,0.35,1.97,0.52


In [40]:
a

array([[-2.58289208,  0.43014843, -1.24082018,  1.59572603],
       [ 0.99027828,  1.17150989,  0.94125714, -0.14692469],
       [ 0.76989341,  0.81299683, -0.95068423,  0.11769564],
       [ 0.20484034,  0.34784527,  1.96979195,  0.51992837]])

In [42]:
a = np.array([2, 1, 5, 7, 4, 6, 8, 14, 10, 9, 18, 20, 22])
a

array([ 2,  1,  5,  7,  4,  6,  8, 14, 10,  9, 18, 20, 22])